# Generated by Django 3.2.19 on 2023-07-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shopowner',
            new_name='shop_owner',
        ),
    ]
