# Generated by Django 3.2.19 on 2023-07-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
