# Generated by Django 3.2.19 on 2023-07-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_shopowner_shop_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_no',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
