# Generated by Django 3.2.19 on 2023-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20230523_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptionfieldy',
            field=models.TextField(default='created at:<function now at 0x7f8d3fbb1c60>'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagefieldy',
            field=models.ImageField(default='product_images/default_image.jpg', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='itemName',
            field=models.CharField(default='created at:<function now at 0x7f8d3fbb1c60>', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='pricefieldy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='quantityfieldy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
